node {
  stage('do something with git') {  
    sshagent (credentials: ['github-key']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs garethjones76@github.com:garethjones76/jenkins-course.git master |awk "{print $1}"'
    }
  }
}
